// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://tdvriqpstgenkihwzniz.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InRkdnJpcXBzdGdlbmtpaHd6bml6Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDQ0ODMyNzQsImV4cCI6MjA2MDA1OTI3NH0.KCbaW9oDY1OqmzWr6vZ1JxREZL00GDuRKaXjgSyisEo";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);